package main.game.action;

public enum AttackingStatus {
	ATTACKING_STATUS_NOT_ENEMY,
	ATTACKING_STATUS_ALREADY_ATTACKED,
	ATTACKING_STATUS_SUCCESS,
	ATTACKING_STATUS_FROZEN,
	ATTACKING_STATUS_NOT_TANK
}
